password as crypto
robsonoduarte/u-vocab-api pull request #63
Opened 2024-07-18 00:20 UTC by Danilosimoes

2024-07-18 00:29 UTC, robsonoduarte requested changes
some bit observation :police_car:

2024-07-18 00:29 UTC, robsonoduarte commented on src/it/java/com/uvocab/api/controller/UserControllerTest.java
> +  @Autowired private PasswordEncoder passwordEncoder;
we don't need this....

2024-07-18 00:29 UTC, robsonoduarte commented on src/it/java/com/uvocab/api/controller/UserControllerTest.java
> +            .setPassword("a")
is really necessary change this value ?

2024-07-18 20:40 UTC, Danilosimoes commented on src/it/java/com/uvocab/api/controller/UserControllerTest.java
> +  @Autowired private PasswordEncoder passwordEncoder;
I forgot to keep it the way it was.

2024-07-19 01:26 UTC, robsonoduarte approved these changes

2024-07-19 16:37 UTC, merged